# Generated by Django 4.2 on 2023-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('mobilenumber', models.BigIntegerField(default=0)),
                ('emailid', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptedCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data_1', models.BinaryField(default=b'')),
                ('encrypted_data_2', models.BinaryField(default=b'')),
                ('encrypted_data_3', models.BinaryField(default=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_ID', models.IntegerField(default=0)),
                ('Name', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('HAEMATOCRIT', models.FloatField(default=0)),
                ('HAEMOGLOBINS', models.FloatField(default=0)),
                ('ERYTHROCYTE', models.FloatField(default=0)),
                ('LEUCOCYTE', models.FloatField(default=0)),
                ('THROMBOCYTE', models.FloatField(default=0)),
                ('MCH', models.FloatField(default=0)),
                ('MCHC', models.FloatField(default=0)),
                ('MCV', models.FloatField(default=0)),
                ('AGE', models.IntegerField(default=0)),
                ('SEX', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
